# Generated by Django 3.1.2 on 2020-10-23 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 10, 23)),
        ),
    ]
