# Generated by Django 3.1.2 on 2020-10-23 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201023_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
